Get process list
vocdoni/vaas-api pull request #11
Opened 2021-12-10 18:46 UTC by NateWilliams2

2021-12-10 18:47 UTC, NateWilliams2 commented
To be merged on top of #10

2021-12-13 09:54 UTC, p4u requested changes

2021-12-13 09:54 UTC, p4u commented on types/api.go
> +	StartBlock      int            `json:"startBlock,omitempty" db:"start_block"`
I think uint32 or uint64 are better for block numbers (since a negative block does not makes sense)

2021-12-13 09:54 UTC, p4u commented on urlapi/entity.go
> +	path := strings.Split(ctx.Request.URL.Path, "/")
Why not declaring this as a URL parameter such as: `https://server/v1/priv/organizations/<organizationId>/elections/<type>`

In general I think a handler should never access directly to `URL.Path`

2021-12-13 09:54 UTC, p4u commented on urlapi/entity.go
> +			log.Errorf("could not get current block height: %v", err)
Let's not log an error if it is already returned (layer below would choose what to do with it, if printing it or not)

2021-12-13 09:54 UTC, p4u commented on urlapi/entity.go
> +			return fmt.Errorf("could not get current block height: %v", err)
Please, wrap the errors correctly with `%w`

Also, wrapping the errors is useful to understand where it was originated. Somethod like `listProcessesPrivateHandler: cannot get current block height: %w`

2021-12-13 09:54 UTC, p4u commented on urlapi/entity.go
> +			if len(tempProcessList) < 64 {
No need to declare cont. 

If cont is false, do we want to keep runing the loop code or should it just break the loop inmediatly? If so, use `break`. 

If you really need keep executing code if cont=false, just use `len(tempProcessList) < 64` as loop condition

2021-12-13 15:11 UTC, p4u commented on urlapi/public.go
> +		cont := true
same code here? I think this method requires also a refactor, its hard to read

2021-12-13 16:08 UTC, NateWilliams2 commented on urlapi/entity.go
> +			return fmt.Errorf("could not get current block height: %v", err)
Do we want to wrap errors returned over HTTP? Imo an integrator getting a message starting with "listProcessesPrivateHandler" provides no meaningful information to them, even though it's helpful to us. I'll work on wrapping these error messages though, for the time being.

2021-12-13 16:37 UTC, p4u commented on urlapi/entity.go
> +			return fmt.Errorf("could not get current block height: %v", err)
Umm, ok you'r right. Let's not add the method name but still use `%w`

2021-12-13 18:09 UTC, p4u requested changes

2021-12-13 18:09 UTC, p4u commented on urlapi/entity.go
> +		return nil, nil, nil, fmt.Errorf("entity %X could not be fetched from the db: %w", entityID, err)
I know this is not a change from this PR, but it would be much friendly if authEntityPermission returns a struct ` {integratorPrivKey,entityID, organization}` instead of 3 unamed parameters.

2021-12-13 18:09 UTC, p4u commented on urlapi/entity.go
> +		newElection.CensusID = ""
can you add a coment to clarify why this field rewrite?

2021-12-13 18:09 UTC, p4u commented on urlapi/public.go
> +			log.Error(fmt.Errorf("could not aggregate results: %w", err))
If what you want is to log a message, then use `%v`instead of `%w`

2021-12-13 18:09 UTC, p4u commented on urlapi/public.go
> +	results *types.VochainResults, meta *types.ProcessMetadata) (process types.APIElectionInfo) {
Please, in general do not use this syntax (define the var on the method signature). It makes code harded to read specially for big functions like this one.

Also try to aggregate as maximum values as possible when creating the var, such as:
```
process := types.APIElectionInfo{ 
 Type: "blind-",
 Title : meta.Title["default"],
 Description : meta.Description["default"],
 }
```

2021-12-13 18:09 UTC, p4u commented on urlapi/public.go
> +		log.Warnf("could not estimate startDate at %d: %s", vc.StartBlock, err.Error())
`%v` is fine for printing err

2021-12-13 18:11 UTC, p4u commented on urlapi/public.go
> +	private bool) (pub []types.APIElectionSummary, priv []types.APIElectionSummary, err error) {
same as before regarding signature vars

2021-12-13 18:14 UTC, p4u commented on urlapi/public.go
> +				return nil, nil, fmt.Errorf("%s not a valid filter", filter)
filter here is either `active, ended, upcoming` so it cannot be wrong, right? if `GetProcessList()` returns an error is not because of the filter

2021-12-13 18:15 UTC, p4u commented on urlapi/public.go
> +				log.Error(err)
add some extra info to this message so it will be easier to find

2021-12-13 18:17 UTC, p4u commented on urlapi/public.go
> +				log.Warn(fmt.Errorf("could not get election,"+
use `%v`and remove fmt.Errorf()

2021-12-13 18:18 UTC, p4u commented on urlapi/public.go
> +	private bool) (privateElections []types.APIElectionSummary,
same

2021-12-13 18:20 UTC, p4u commented on urlapi/public.go
> +		priv = append(priv, reflectElectionPrivate(*newProcess))
`return append(priv, reflectElectionPrivate(*newProcess), nil` looks better to me (and remove the else case)

2021-12-13 18:21 UTC, p4u commented on urlapi/public.go
> +			priv = append(priv, reflectElectionPublic(*newProcess))
`return append(priv, reflectElectionPublic(*newProcess), nil`

2021-12-13 18:22 UTC, p4u commented on urlapi/public.go
> +	return priv, pub
`return nil, append(pub, reflectElectionPublic(*newProcess))`

Please, add comments to the returns

2021-12-13 18:23 UTC, p4u commented on vocclient/vocclient.go
> +func (c *Client) FetchOrganizationMetadata(URI string) (entity *types.EntityMetadata, _ error) {
upss... why all these var definitions in function signature? I don't see the point sorry :(

2021-12-13 18:24 UTC, p4u commented on vocclient/vocclient.go
> +
blank line

2021-12-13 18:25 UTC, p4u commented on vocclient/vocclient.go
> +		return "", fmt.Errorf("%s: %v", "sumbitRawTx", err)
`fmt.Errorf("submitwarTx error: %w", err)`

2021-12-13 18:27 UTC, p4u commented on vocclient/vocclient.go
> +		tctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
make this 1*time.Minute a constant (better try to reduce magic numbers at minimum)

2021-12-13 18:28 UTC, p4u commented on vocclient/vocclient.go
> +	if gw.client.WS != nil {
Are we using Websockets? The httpRouter does not provide WS support AFAIK, so the Gateway connection won't work. Also we moved away in general from WS in favor of HTTP

2021-12-13 18:29 UTC, p4u commented on vocclient/vocclient.go
> +	log.Debugf("response: %s", message)
response to what?

2021-12-13 22:21 UTC, p4u requested changes

2021-12-13 22:21 UTC, p4u commented on urlapi/util.go
> +	process.Status = strings.ToTitle(models.ProcessStatus_name[vc.Status])[0:1] +
we should check `models.ProcessStatus_name[vc.Status]`before accessing to a specific position (it could be empty?)

2021-12-13 22:21 UTC, p4u commented on urlapi/util.go
> +			log.Errorf("could not aggregate results: %v", err)
IMO this method should return an error and all these log.Errorf and some warnings should return (else it will be hard to find bugs here, the logs are hard to follow sometimes).

2021-12-13 22:21 UTC, p4u commented on urlapi/util.go
> +	process.Ok = true
I don't understand this. There is not any return so the execution will always get here...

2021-12-13 22:21 UTC, p4u commented on urlapi/util.go
> +	currentHeight, err := u.vocClient.GetCurrentBlock()
I would add here a big TODO for vocClient: do save the current block in memory and update it once every 10 seconds or so

2021-12-13 22:21 UTC, p4u commented on urlapi/util.go
> +		blk, err := u.vocClient.GetBlock(height)
same for block... that's gonna be very consuming, it won't scale

2021-12-13 22:37 UTC, NateWilliams2 commented on urlapi/util.go
> +		blk, err := u.vocClient.GetBlock(height)
we can't cache this block, as it's the block at our target height, not the current height. So there's no way to know which block to cache ahead of time. 
This line of code fetches the block only to get the exact timestamp of that block height. We could alternatively either
- estimate block times of heights in the past (like we do for those in the future), rather than getting the exact value
- implement a gateway API call that returns just the timestamp for a given block

2021-12-14 17:00 UTC, p4u requested changes

2021-12-14 17:00 UTC, p4u commented on vocclient/vocclient.go
> +	var req api.APIrequest
`req := api.APIrequest{ Method: .... }`

2021-12-14 17:04 UTC, emmdim commented on vocclient/vocclient.go
> +	defer c.blockHeight.lock.Lock()
yeah yeah. Stupid copy paste

2021-12-14 19:27 UTC, merged

2021-12-14 20:46 UTC, p4u commented on vocclient/vocclient.go
> +func (c *Client) AddClaimBulk(censusID string, censusSigners []*ethereum.SignKeys, censusPubKeys []string, censusValues []*dvoteTypes.BigInt) (root dvoteTypes.HexBytes, invalidClaims []int, _ error)
line too long