Get Tx Status
vocdoni/vaas-api pull request #16
Opened 2021-12-16 20:53 UTC by NateWilliams2

- Handlers that submit transactions to the vochain (createOrganization, updateOrganization, createProcess, setProcessStatus) create a tx hash and add it to a map, along with the time of tx creation
- Handlers that submit txs and update the database store the database queries on a sync.Map
- GetTransactionStatus handler determines if a transaction has been "mined" (if it was created more than 15 seconds ago) and submits the pending database query if so

2021-12-17 10:13 UTC, p4u requested changes

2021-12-17 10:13 UTC, p4u commented on urlapi/txhash.go
> +	mined := false
`mined := ok && txTime.Add(15*time.Second).Before(time.Now())`

2021-12-17 10:13 UTC, p4u commented on urlapi/txhash.go
> +	if mined {
reverse this logic, it makes code easier to read:

`if !mined { return ... }`

2021-12-17 10:13 UTC, p4u commented on urlapi/urlapi.go
> +	txWaitMap map[string]time.Time
This map seems racy

2021-12-22 16:44 UTC, p4u approved these changes

2021-12-22 16:44 UTC, p4u commented on types/api.go
> +	TxHash           string               `json:"txHash,omitempty"`
Wouldn't be better to use types.HexBytes here?

2021-12-22 16:45 UTC, p4u commented
I think the typescript part might require @brickpop review, but up to you.

2021-12-22 17:00 UTC, NateWilliams2 commented on types/api.go
> +	TxHash           string               `json:"txHash,omitempty"`
The client would only ever use this to query for the tx status, in which case they would append the txHash string to the request URL. So from their perspective, a string is fine. Also, we use the txHash as a string internally in the tx maps on the API server, so we will have to convert the txHash to a string when we receive it from the vochain anyways. I'm fine changing it to HexBytes, but more type conversion would be required than the current case.

2021-12-22 17:18 UTC, emmdim commented
> I think the typescript part might require @brickpop review, but up to you.

He can review in a later iteration. It works btw

2021-12-22 18:04 UTC, merged