[wip] Feat/private metadata
vocdoni/vaas-api pull request #24
Opened 2021-12-20 16:16 UTC by NateWilliams2

2021-12-21 20:27 UTC, p4u requested changes

2021-12-21 20:27 UTC, p4u commented on urlapi/public.go
> +	compressedSaltedKey, err := ethereum.CompressPubKey(
I think it makes more sense to compare the uncompressed pubkeys, it requires less steps

2021-12-21 20:27 UTC, p4u commented on urlapi/urlapi.go
> +			log.Errorf("could not decode global metadata key: %v", err)
Error will continue the execution. I think this should be a Fatal()

2021-12-21 20:27 UTC, p4u commented on urlapi/urlapi.go
> +		} else {
Also if fatal, there is no need for this else

2021-12-21 20:27 UTC, p4u commented on vocclient/vocclient.go
> +	return &process, nil
`return &process, json.Unmarshal(decrypted, &process)`

2021-12-21 20:27 UTC, p4u commented on vocclient/vocclient.go
> +	return metaURI, nil
```
return c.AddFile(metaBytes, "ipfs",
		fmt.Sprintf("%X process metadata (encrypted)", processId))
```

2021-12-21 20:27 UTC, p4u commented on types/api.go
> +type RawFile struct {
Please, add comments to all exported types and methods :1st_place_medal:

2021-12-21 20:27 UTC, p4u commented on urlapi/entity.go
> +		if metaPrivKeyBytes, err = hex.DecodeString(metadataPrivKey); err != nil {
`if metaPrivKeyBytes, err = hex.DecodeString(dvoteutil.RandomHex(32)); err != nil {`

2021-12-21 20:27 UTC, p4u commented on urlapi/entity.go
> +	var encryptedMetaKey []byte
Is this var needed? why not using `metaPrivKeyBytes`?

2021-12-21 20:27 UTC, p4u commented on urlapi/entity.go
> +	} else {
please, add also comments to the else

2021-12-21 20:27 UTC, p4u commented on urlapi/entity.go
> +	if dbElection.Confidential {
When if/else are so big, I think we should add comments to explain what's happening inside the if statement

2021-12-21 20:27 UTC, p4u commented on urlapi/public.go
> +	if err != nil {
`if err := verifyCspSharedSignature(processId, cspSignature, vochainProcess.CensusRoot)`

2021-12-21 20:27 UTC, p4u commented on urlapi/public.go
> +		metaKey := dbElection.MetadataPrivKey
Looks like I'm reading the same code several times. Maybe abstract this into a function?

2021-12-22 20:32 UTC, emmdim commented on types/types.go
> +	CreatedUpdated   `json:"created_updated,omitempty"`
@NateWilliams2  This is incorrect. Created updated is defined earlier and imported here

2021-12-23 10:54 UTC, p4u commented on vocclient/vocclient.go
> +	log.Debugf("encrypting meta with %x", metadataPrivKey)
Lets not print the private key in the logs if possible

2021-12-23 10:54 UTC, p4u approved these changes

2021-12-23 14:01 UTC, emmdim commented on database/pgsql/elections.go
> +	selectIntegrator := `SELECT metadata_priv_key, title, census_id, start_date, end_date, start_block, end_block, confidential, hidden_results,
@NateWilliams2  why this is added here since it is returned also in the `getElectionPrivate`?

2021-12-23 15:52 UTC, emmdim approved these changes

2021-12-23 16:16 UTC, merged