Integration test
vocdoni/vaas-api pull request #33
Opened 2022-01-04 22:13 UTC by NateWilliams2

So far this PR sets up an integration test suite with a Vocone instance and a CSP running. It then starts a VaaS API server connected to these services.

2022-01-07 09:01 UTC, mvdan reviewed
It might help considerably to mark tests as parallel where possible: https://pkg.go.dev/testing#T.Parallel

Ideally, the tests that share the postgres DB should run in parallel. For example, if they want to create entities and processes, they could create unique ones (e.g. prefixed with their test name), that way they wouldn't conflict.

2022-01-07 09:01 UTC, mvdan commented on test/testpgsql/pgsql_test.go
> +	if err := API.Start(db, "", "", "", 9000); err != nil {
Should TestMain end with an API "stop", or does the main process exiting already kill postgres?

Do we leave the postgres data behind? If so, I think we should delete it. Perhaps the easiest way would be to tell postgres to use a https://pkg.go.dev/testing#T.TempDir for its data.

2022-01-07 15:01 UTC, NateWilliams2 commented on test/testpgsql/pgsql_test.go
> +	if err := API.Start(db, "", "", "", 9000); err != nil {
@mvdan we're actually not running postgres from the golang test files. When I test locally, I simply run a postgres server. For the golang CI, we're trying to get a postgres docker image working that can be used by the tests.

2022-01-07 15:09 UTC, mvdan commented on test/testpgsql/pgsql_test.go
> +	if err := API.Start(db, "", "", "", 9000); err != nil {
Ah, sounds good. If one runs the tests locally via `go test ./...`, do these tests get skipped?

Something I've done in this scenario in the past is make the tests require the database if an env var like TEST_DB is set to the db conn string, and otherwise skip them. This gets you the tests skipping by default, and never skipping on CI where the env var is set.

2022-01-07 15:18 UTC, NateWilliams2 commented on test/testpgsql/pgsql_test.go
> +	if err := API.Start(db, "", "", "", 9000); err != nil {
yep, right now we actually just skip the tests if there's no connection to a db available

2022-01-11 22:11 UTC, emmdim requested changes

2022-01-11 22:47 UTC, NateWilliams2 commented on test/testcommon/util.go
> +type testOrganization struct {
It's just simplicity. For the purpose of testing it's simplest to store data in one place that we usually don't store in one place. Therefore there's no existing type that works. For example, the Organization type that we use to store items in the db does not include the name or description.

2022-01-11 22:49 UTC, NateWilliams2 commented on test/testcommon/apis.go
> +		httpRouter.PrometheusID = "api-chi"
The prometheus ID needs to be unique, but we're using multiple HTTP routers here for testing. So here we're simply changing the default prometheus ID so it doesn't conflict with the other instances.

2022-01-12 00:05 UTC, NateWilliams2 commented on urlapi/public.go
> +	return fmt.Errorf("endpoint %s unimplemented", ctx.Request.URL.String())
this is something i'll make a note of to you- I realized this method was not working, as it assumed there's an Integrator API token in order to fetch the organization. We'll need a public getOrganization method in the db to enable this API call.

2022-01-12 00:05 UTC, NateWilliams2 commented on test/testcommon/util.go
> +func CreateDbOrganizations(size int) []*types.Organization {
same as above- for db testing we want to create organizations to go directly into the db. For API testing, we need other information.

2022-01-12 20:37 UTC, emmdim commented on test/testcommon/apis.go
> +		httpRouter.PrometheusID = "api-chi"
@NateWilliams2 So i understand it is not possible to disable the prometheus logging (this is what it refer's to, right?)

2022-01-12 20:49 UTC, NateWilliams2 commented on test/testcommon/apis.go
> +		httpRouter.PrometheusID = "api-chi"
exactly

2022-01-12 20:49 UTC, NateWilliams2 commented on test/testcommon/apis.go
> +		httpRouter.PrometheusID = "api-chi"
I could look into modifying @p4u 's httprouter package to allow for disabling prometheus

2022-01-12 21:09 UTC, p4u commented on test/testcommon/apis.go
> +		httpRouter.PrometheusID = "api-chi"
The prometheus service here is passive, meanning that it will only add an HTTP endpoint (it won't do any query to any server). So I don't see the problem.

In any case we can change the bahavior, if the PrometheusID is empty (default), just don't add the endpoint on the go-chi side.

2022-01-13 16:13 UTC, NateWilliams2 commented
@mvdan 
> starting the services we need directly via the Go API seems fine to me

do you mean running a go execution of a command to start up a vocone and a CSP in other processes? If so, that's a good point. I'll try to do that.

2022-01-13 16:21 UTC, NateWilliams2 commented on test/testapi/api_election_test.go
> +func TestElectionList(t *testing.T) {
nope, just missed this by mistake

2022-01-13 16:26 UTC, mvdan commented
> do you mean running a go execution of a command to start up a vocone and a CSP in other processes? If so, that's a good point. I'll try to do that.

Oh, I meant the opposite, that doing it in-process like you're doing now seems fine :P Using separate processes could also work, if it helps for one reason or another. Note that you would lose the code coverage from them though. Debugging could also get a bit harder, as you'd now juggle multiple processes.

2022-01-13 16:35 UTC, NateWilliams2 commented
@mvdan 
> Oh, I meant the opposite, that doing it in-process like you're doing now seems fine :P

Ok wonderful :)

2022-01-13 22:20 UTC, mvdan approved these changes
SGTM! Just some more nits.

By the way, I noticed that running `go test ./...` locally with no setup fails. I think that should succeed rather quickly, noticing that postgres isn't running and skipping all of those tests.

I still think the easiest way to do that is:

* If a special env var like TEST_POSTGRES is set with the database host details, we *must* run the integration tests, and either succeed or fail.
* If that env var isn't set (like in my case above), we immediately skip the integration tests

This works nicely because, if CI sets that env var, then we're pretty sure that CI will never skip the tests. If we try to make it like "skip the tests if the DB doesn't respond", then CI could silently stop running the integration tests.

2022-01-13 22:20 UTC, mvdan commented on test/testapi/api_election_test.go
> +	err := json.Unmarshal(respBody, &electionList)
every DoRequest call is followed by an Unmarshal, so you could consider passing a "response type" pointer as the last parameter to save 2-3 lines per call site.

2022-01-13 22:20 UTC, mvdan commented on test/testapi/api_public_test.go
> +	nonce, err := hex.DecodeString(dvoteutil.RandomHex(32))
do we not have a "random bytes" helper func? generating random bytes, encoding them as hex, and decoding them again seems a bit unnecessary :)

2022-01-13 22:20 UTC, mvdan commented on test/testapi/api_public_test.go
> +	nonce, err := hex.DecodeString(dvoteutil.RandomHex(32))
ditto

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/util.go
> +		cspPubKey, _ := hex.DecodeString(cspPub)
ditto (probably more places too?)

2022-01-13 22:20 UTC, mvdan commented on test/testapi/api_public_test.go
> +		Nonce: util.RandomHex(32),
careful, you're importing the dvote/util package twice, under different names. I think staticcheck warns about this, so you should run it and ensure it's happy.

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/services.go
> +	go vc.Start()
do we care about waiting until vocone is ready?

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/services.go
> +	vc.SetBlockSize(500)
would be good to document how you arrived at these numbers; e.g. I imagine that 1s is a decent balance between reasonably fast tests and not burning too much CPU generating new blocks, but it's just a guess.

2022-01-13 22:20 UTC, mvdan commented on test/testapi/api_test.go
> +	storage := os.TempDir()
Hmm, I wouldn't store directly under /tmp; see ioutil.TempDir which creates a temporary dir. You should also delete it when you're done. Remember that defers don't run when calling os.Exit, so you might want to call the removal manually without defer.

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/services.go
> +	router.PrometheusID = "csp-chi"
I seem to recall this is a special string for a good reason; document it?

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/services.go
> +	TEST_CSP_PORT = 5000
This kind of spelling for global constants comes from Java, but it doesn't really exist in Go :) I'd just use testHost, testGatewayPath, etc.

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/services.go
> +	dir := path.Join(t.StorageDir, "auth")
remember that you want filepath, not path, for paths on disk

2022-01-13 22:20 UTC, mvdan commented on test/testcommon/util.go
> +	return hex.EncodeToString(signature)
nit: I'd just return the []byte here, and use %x with fmt.Sprintf at the call site. Go has proper byte slice types, so there's no need to use hex strings everywhere by default.

2022-01-17 16:30 UTC, merged