Store proofType for blind/signed processes
vocdoni/vaas-api pull request #36
Opened 2022-01-14 20:59 UTC by NateWilliams2

2022-01-18 20:34 UTC, emmdim commented on database/pgsql/migrations.go
> +    proof_type TEXT NOT NULL,
@NateWilliams2 Considering an already deployed database the original migarition cannot be changed. The right practice is to create a new migration and declare there the changes. For example check:
https://github.com/vocdoni/vocdoni-manager-backend/blob/master/database/pgsql/migrations.go#L259

Otherwise the database needs to be deleted and recreated. I can commit the corresponding migration together with some changes i intented to add

2022-01-18 20:38 UTC, emmdim commented on types/api.go
> +	PROOF_TYPE_ECDSA = "ecdsa"
@NateWilliams2  it could even be an enumeration type (with the string assignemnts as is). Btw how are the no-proof/open processes declared?

2022-01-18 20:43 UTC, emmdim commented on urlapi/util.go
> +		for {
@NateWilliams2 I think the process downloading makes sense to be in a a helper funcion. Probably it is being reused elsewhere

2022-01-18 20:45 UTC, emmdim commented on urlapi/api_helpers_test.go
>  }
@NateWilliams2 Are there extra tests for blind and singed missing?

2022-01-18 20:49 UTC, NateWilliams2 commented on types/api.go
> +	PROOF_TYPE_ECDSA = "ecdsa"
no-proof? As in no interaction with the CSP, anyone can submit a vote? I didn't know that was a type

2022-01-18 20:52 UTC, NateWilliams2 commented on database/pgsql/migrations.go
> +    proof_type TEXT NOT NULL,
ah, ok. I didn't know this. That would be great if you could

2022-01-18 20:54 UTC, emmdim commented on urlapi/util.go
> +			case "BLIND":
@NateWilliams2  maybe the switch is exagerated here? how about:
```if filter == "BLIND" and newProcess.ProofType == "blind"{
      appendProcess(&electionList, newProcess, private, "")
}
...```

Except if there needs to be a third case in the end about the processes without proof, then you could explit the default case and it would make more sense

2022-01-18 20:59 UTC, emmdim requested changes
Please consider the requested changes :-)

2022-01-18 21:24 UTC, emmdim commented on database/pgsql/migrations.go
> +    proof_type TEXT NOT NULL,
Btw maybe a default value should be assigned. Wil lleave this pending till we decide on https://github.com/vocdoni/vaas-api/pull/36#discussion_r787145465

2022-01-18 21:56 UTC, NateWilliams2 commented on urlapi/util.go
> +			case "BLIND":
ahh yep, that switch had a purpose at one point and now does not. Surprised staticcheck doesn't catch that.

2022-01-18 22:10 UTC, NateWilliams2 commented on urlapi/api_helpers_test.go
>  }
we do test them, but in the integration tests, not the internal logic tests

2022-01-19 17:21 UTC, NateWilliams2 commented on database/pgsql/migrations.go
> +    proof_type TEXT NOT NULL,
I think the default value should be ecdsa, as that's the most basic. In either case, the handlers will always set it.

2022-01-19 17:22 UTC, NateWilliams2 commented on types/api.go
> +	PROOF_TYPE_ECDSA = "ecdsa"
Pau messaged in discord that we cannot enable this, as it leaves open a vulnerability for spam

2022-01-31 21:13 UTC, emmdim commented on urlapi/entity.go
> +	default:
@NateWilliams2  If no type is specified maybe we should assume a default one ourselves?

2022-01-31 21:33 UTC, emmdim commented on urlapi/entity.go
> +	default:
Let's leave it as is for now.

2022-01-31 21:37 UTC, emmdim commented on urlapi/util.go
> +		fullProcessList, err := u.fetchProcessList(entityId, filter)
@NateWilliams2  think there can be some small restructuring to make the swtich cases more understanbable. All tha cases share the outside loop of fewtching the processes from the DB. Maybe the switch could happen inside the loop to avoid repeating code

2022-01-31 21:49 UTC, NateWilliams2 commented on urlapi/util.go
> +		fullProcessList, err := u.fetchProcessList(entityId, filter)
attempted to fix this in commit a100d14

2022-02-03 20:18 UTC, merged