Use serializable transaction interface for cached db transactions
vocdoni/vaas-api pull request #39
Opened 2022-01-20 17:21 UTC by NateWilliams2

2022-01-20 20:21 UTC, emmdim commented on database/transactions/serializable.go
> +	var objMap map[string]*json.RawMessage
@NateWilliams2  I do not understand this map. Is this the entire storage of pending transactions?

2022-01-20 20:23 UTC, NateWilliams2 commented on database/transactions/serializable.go
> +	var objMap map[string]*json.RawMessage
no. this is the raw map version of the SerializableTx. We need this because the `tx.Body` could be any type, so we need to check which `tx.Type` this object is before deserializing it.

2022-01-20 20:49 UTC, emmdim commented on database/transactions/serializable.go
> +	Body TxBody             `json:"body"`
@NateWilliams2 I am confused a bit with the typing. The TxBody is an interface that applies to the body, and implemented by CreateelectionTx etc? Is it somwhere explicited that CreateElectionTx implements TxBody?

2022-01-20 21:07 UTC, NateWilliams2 commented on database/transactions/serializable.go
> +	Body TxBody             `json:"body"`
no, good point. I'll make that explicit. You're understanding it right.

2022-01-20 21:25 UTC, emmdim commented on database/transactions/serializable.go
> +	err = json.Unmarshal(*objMap["type"], &tx.Type)
@NateWilliams2 not sure about the unrmashal syntax, but I have the feeling that this would cause a second (recursive) unmarshall? Is that correct? If that is the case then I think something is going wrong. Maybe we need a design similar to here with reqOuter and reqInner:
https://github.com/vocdoni/vocdoni-node/blob/1a8914039ad0359ff69b3124cb86bd6187cf488f/multirpc/router/router.go#L109

2022-01-20 21:25 UTC, emmdim commented on database/transactions/serializable.go
> +	err = json.Unmarshal(*objMap["type"], &tx.Type)
MAybe this had to do with the map comment as well :-)

2022-01-20 21:31 UTC, NateWilliams2 commented
I've tested that the recent changes allow you to shut down the server before a tx has been mined, then restart it later and commit that tx to the database.

2022-01-21 20:44 UTC, NateWilliams2 commented
The latest two commits make the following changes:
- Run a goroutine that is periodically (every 5s) monitoring the serializableTx key-value store. For each entry, it check if the transaction associated with this database query has been mined on the vochain. If so, it commits the serializedTx to the database and then deletes it from the KV.
- Do not edit the database from the getTransactionStatus handler. Instead: first, check if the given transaction has been mined on the vochain. If it has, then look at the serializableTx key-value store. If an entry exists for the given tx hash, then the goroutine hasn't yet gotten to committing that serializableTx and is likely sleeping for 5s. Report that the transaction has not been mined, even though it has been mined on the vochain, so that we don't have an inconsistency where the user sees that the transaction has been mined, but the result of the transaction (eg. creating an organization) has not yet been committed to the database. At most, the user would then have to wait another 5 seconds before the transaction is reported as committed. 

@emmdim and I are in an ongoing discussion of whether this is the right design. @p4u @mvdan what do you think? happy to discuss other potential solutions next week.

2022-01-27 09:06 UTC, p4u requested changes

2022-01-27 09:06 UTC, p4u commented on database/transactions/kv.go
> +func StoreTx(kv dvotedb.Database, hash []byte, query SerializableTx) error {
You are explicitly passing `kv` on all this methods. I would do it implicit, so create a type (which can just inherit from dvotedb.Database) with this extra methods (GetTx, StoreTx).

2022-01-27 09:06 UTC, p4u commented on database/transactions/kv.go
> +	hash = append([]byte(TxPrefix), hash...)
This way you are modifying "hash", that's in general not a good approach since the caller do not expect it (unless you document the method properly). 

In any case you don't need to modify hash, you can just do `queryBytes, err := tx.Get(append([]byte....))`

2022-01-29 06:00 UTC, mvdan commented
The five-second polling seems fine to me. We could certainly do better in the future, but I don't see that as something we must do today. For example:

> If an entry exists for the given tx hash, then the goroutine hasn't yet gotten to committing that serializableTx and is likely sleeping for 5s.

an incremental change we could consider in the future is to have that goroutine run every 5s via a timer, and then getTransactionStatus can kick the timer to force it to run ASAP if you get to such an edge case situation. I don't think it's a must-have, but it could mean that you reduce the wait time from ~5s to ~1s or less.

2022-01-29 06:02 UTC, mvdan commented on database/transactions/serializable.go
> +	err = json.Unmarshal(*objMap["type"], &tx.Type)
It seems fine to me, but I'd use a struct rather than a map for objMap, since you already know there should just be two JSON keys - type and body. Beyond being simpler, you also avoid having to unmarshal the type valeu twice, as you can just make it a string field.

2022-01-29 09:07 UTC, mvdan reviewed
First pass :) Will do another later.

2022-01-29 09:07 UTC, mvdan commented on database/transactions/election.go
> +	EndBlock          int
nit: best to use fixed sizes like int32/int64, otherwise the behavior here will change depending on 32 bit vs 64 bit, and you don't want that kind of unpredictability with DBs or APIs.

2022-01-29 09:07 UTC, mvdan commented on database/transactions/election.go
> +	_, err := (*db).CreateElection(tx.IntegratorPrivKey,
I think you should be able to just call `db.CreateElection(...)`; if that doesn't work, then I'm not sure why we're using a db pointer at all.

2022-01-29 09:07 UTC, mvdan commented on database/transactions/kv.go
> +	Db  dvotedb.Database
nit: spell these DB, not Db; same in TxCacheDB

2022-01-29 09:07 UTC, mvdan commented on database/transactions/kv.go
> +	Mtx *sync.RWMutex
assuming this mutex protects the entire struct, you can embed it so one can lock and unlock the entire thing without accessing the field.

also, no need for the pointer, I think.

2022-01-29 09:07 UTC, mvdan commented on database/transactions/kv.go
> +	if err = json.Unmarshal(queryBytes, &serializableTx); err != nil {
nit: try to always use `:=` in `if` declarations

2022-01-29 09:07 UTC, mvdan commented on database/transactions/organization.go
> +	PublicApiQuota    int
same as before

2022-01-30 10:14 UTC, mvdan approved these changes
Code wise SGTM; I think I've left you enough nits :)

2022-01-30 10:14 UTC, mvdan commented on database/transactions/transactions_test.go
> +	storage, err := ioutil.TempDir("/tmp", ".transactions-test")
```suggestion
	storage, err := ioutil.TempDir("", ".transactions-test")
```

The temp dir default is fine, and will also work on e.g. Windows.

2022-01-30 10:14 UTC, mvdan commented on database/transactions/kv.go
> +func NewTxKv(db dvotedb.Database, mutex *sync.RWMutex) TxCacheDb {
every single caller passes in a new mutex; why pass the mutex at all? just have the constructor create it.

2022-01-30 10:14 UTC, mvdan commented on database/transactions/kv.go
> +func NewTxKv(db dvotedb.Database, mutex *sync.RWMutex) TxCacheDb {
(or create nothing, because the mutex field probably doesn't need to be a pointer, either)

2022-01-30 10:14 UTC, mvdan commented on database/transactions/kv.go
> +	if err == dvotedb.ErrKeyNotFound {
nit: use `errors.Is` whenever you want to compare errors to sentinel values. the only exceptions should be `nil` and `io.EOF`.

2022-01-30 10:14 UTC, mvdan commented on urlapi/urlapi.go
> +	kv dvotedb.Database, client *vocclient.Client) error {
thinking outloud - if funcs take two databases, I worry that we might pass them in the wrong order by mistake. you could reduce the chances by using different types or by putting the new kv argument at the end.

2022-01-30 10:14 UTC, mvdan commented on database/transactions/kv.go
> +func NewTxKv(db dvotedb.Database, mutex *sync.RWMutex) TxCacheDb {
also, the constructor should return a pointer, since the methods all work on a pointer as well.

2022-01-30 10:14 UTC, mvdan commented on database/transactions/organization.go
> +	AvatarUri         string
nit: use URI instead of Uri, just like DB, API, etc.

2022-01-30 10:14 UTC, mvdan commented on test/testapi/api_test.go
> +	log.Info(string(respBody))
remember to use t.Log or t.Logf for the tests, to attach the logs to each test result

2022-01-30 23:14 UTC, p4u approved these changes
Great work @NateWilliams2!!

2022-01-30 23:17 UTC, p4u commented on database/transactions/transactions_test.go
> +	storage, err := ioutil.TempDir("/tmp", ".transactions-test")
Even if /tmp is valid I think its better to just leave the field empty, OS will provide it.

2022-01-30 23:18 UTC, p4u commented on urlapi/urlapi.go
>  const API_VERSION string = "v1"
Nit: we should use camelcase for constants

2022-01-30 23:20 UTC, p4u commented on database/transactions/election.go
> +	_, err := (*db).CreateElection(tx.IntegratorPrivKey,
database.Database is actually an interface, so no pointer should be used (interface is already a pointer)

2022-01-31 15:48 UTC, NateWilliams2 commented on database/transactions/kv.go
> +	Mtx *sync.RWMutex
ooh, that's a really nice design pattern I'll use in the future :)

2022-01-31 18:13 UTC, merged